version: 1
formatters:
  simple:
    format: '%(asctime)s - %(filename)s:%(lineno)3s %(funcName)20s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: /tmp/iwubi.log
    maxBytes: 1048576
    backupCount: 3
loggers:
  werkzeug:
    level: DEBUG
    handlers: ['console', 'file']
    propagate: no
root:
  level: DEBUG
  handlers: ['console', 'file']